apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
# The env vars below can be passed into a pod using the envFrom pod spec.
# These global variables can be used to parameterize your deployments.
# The FQDN and URLs here should match your ingress or istio gateway definitions
data:
  FQDN: $(NAMESPACE).iam.example.com
  SUBDOMAIN: iam
  DOMAIN: example.com
  AM_URL: https://$(NAMESPACE).iam.example.com/am
  IDM_ADMIN_URL:  https://$(NAMESPACE).iam.example.com/admin
  IDM_REST_URL:   https://$(NAMESPACE).iam.example.com/openidm
  ENDUSER_UI_URL:   https://$(NAMESPACE).iam.example.com/enduser
